version: '3.7'

services:
  app:
    build: ./api
    # command: uvicorn main:app --host 0.0.0.0 --port 80
    # volumes:
    #   - .:/usr/src/personalised_nudges
    ports:
      - 80:80
    depends_on:
      - db

  db:
    # build: ./db
    image: mysql:5.7
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=password
      - MYSQL_USER=jechu
    expose: 
      - 3306

volumes:
  mysql_data: